### ISSUE TITLE
Useful Info

### ISSUE THREAD

**Issue by samster395** [K4CZP3R/tapo-p100-python#2]
For me I had to make sure the plug is on firmware version 1.3.4, one of mine was and worked fine the other was not so I had to update it and then remove and set it up again for it work.

Also for the windows install I just tried to run the main.py and it failed saying could not find jsons package so I installed that then all worked fine, might be useful for others trying to run on Windows.

Thanks for making this :)

**Comment by kacper-serewis** [comment]
I personally running it through Linux, feel free to add a note in the readme about windows installation.
I have no info about firmware version breaking this script.
