### ISSUE TITLE
Device responded with: {'error_code': 1003}

### ISSUE THREAD

**Issue by Mysteoa** [K4CZP3R/tapo-p100-python#9]
I found about this project from OctoPrint plugin PSUControl-Tapo.
It stopped working a few days ago, and I'm investigating what the issue is.

From the plugin debug and from testing with your script, I get the same error - 1003. It looks like it failing the handshake.
It works fine from the app. I don't know if the Smart plug was updated, it's currently using FW ver. 1.2.1 build 230804 re. 190922

**Comment by miumer** [comment]
Same issue here

**Comment by sachinpatil280** [comment]
@K4CZP3R can you please update for this issue?

**Comment by kacper-serewis** [comment]
Yes, you should use actively maintained python library https://github.com/petretiandrea/plugp100
